apiVersion: v1
kind: Template
metadata:
  name: ${PARAM_APP_NAME}-template
  annotations:
    openshift.io/display-name: Node Js TEST
    iconClass: fa fa-code
objects:

###############################################################################
# Definición de IMAGESTREAM
###############################################################################
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${PARAM_IMAGE_NAME}
    
    
###############################################################################
# Definición de BUILD CONFIG
###############################################################################
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: ${PARAM_IMAGE_NAME}:latest
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 1Gi
        

###############################################################################
# Definición de SERVICE ACCOUNT
###############################################################################
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pltesting-k8s-sa
    


      
    
###############################################################################
# Definición de DEPLOYMENT CONFIG
###############################################################################
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    template:
      metadata:
        labels:
          deploymentConfig: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:

        containers:
          - name: ${PARAM_APP_NAME}
          
            env:
              - name: ENVIRONMENT
                value: ${ENVIRONMENT}
                
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
                    
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
                            
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
                    
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
                    
              - name: MY_CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    resource: requests.cpu
                    
              - name: MY_CPU_LIMIT
                valueFrom:
                  resourceFieldRef:
                    resource: limits.cpu
                    
              - name: MY_MEM_REQUEST
                valueFrom:
                  resourceFieldRef:
                    resource: requests.memory
                    
              - name: MY_MEM_LIMIT
                valueFrom:
                  resourceFieldRef:
                    resource: limits.memory


            envFrom:
              - configMapRef:
                  name: ${PARAM_APP_NAME}-config
              - configMapRef:
                  name: graylog-config

                  
            image: ${PARAM_IMAGE_NAME}:latest
            
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
                
            # livenessProbe:
            #   failureThreshold: 3
            #   initialDelaySeconds: 40
            #   periodSeconds: 10
            #   successThreshold: 1
            #   httpGet:
            #     httpHeaders:
            #       - name: Authorization
            #         value: Basic aGVhbHRoY2hlY2s6WjEwTjAxMDE=
            #     path: /actuator/health
            #     port: 8080
            #     scheme: HTTP
            #   timeoutSeconds: 5
              
            # readinessProbe:
            #   failureThreshold: 3
            #   initialDelaySeconds: 30
            #   periodSeconds: 10
            #   successThreshold: 1
            #   httpGet:
            #     httpHeaders:
            #       - name: Authorization
            #         value: Basic aGVhbHRoY2hlY2s6WjEwTjAxMDE=
            #     path: /actuator/health
            #     port: 8080
            #     scheme: HTTP
            #   timeoutSeconds: 5
                      
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 256Mi
    triggers: []
    replicas: 1
    strategy:
      type: Rolling
      
          
###############################################################################
# Definición de SERVICE
###############################################################################
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
    

###############################################################################
# Definición de ROUTES
###############################################################################

# Ruta *.apps-(re|rp).cloudteco.com.ar
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
    annotations:
      description: Ruta que expone al servicio de prueba
      haproxy.router.openshift.io/timeout: 180s
        
  spec:
    to:
      kind: Service
      name: ${PARAM_APP_NAME}
      weight: 100
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None



###############################################################################
# Definición de CONFIG MAP
###############################################################################
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-config
  data:
    TZ: America/Argentina/Buenos_Aires
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    http_proxy: ""
    https_proxy: ""

###############################################################################
# Definición de PARÁMETROS DEL TEMPLATE
###############################################################################    
parameters:
- name: PARAM_APP_NAME
  required: true
  value: ${PARAM_APP_NAME}
  
- name: PARAM_IMAGE_NAME
  required: true
  value: ${PARAM_IMAGE_NAME}
  
- name: GIT_REPO
  required: true
  value: https://github.com/hellraiserii/nodejs-ocp3-test.gi
  
- name: GIT_BRANCH
  required: true
  value: master
  
- name: ENVIRONMENT
  required: true
  value: DEV
  
  
